---
title: "HW6"
author: "Li Ruan"
---
******
1) Plot a pair of blue histograms with a vertical red line at the mean (one using counts and the other density) for every numerical variable at each bin size specified in the bin sizes input parameter. You can plot individually or as a grid. If you chose to plot as a grid, there should be separate grids for each count-bin size combination and separate grids for each density-bin size combination. For example, given 5 numeric variables and a vector of three bin sizes will generate 30 individual plots or a total of 6 grid plots (with each grid plot containing 5 subplots).
2) Plot a gray bar graph for every categorical and binary variable.
3) Calculate the r2 (r-square) value for every pair of numerical
variables.
4) Return the following in an R list:
a. A frequency table for every categorical and binary variable b. Fornumericalvariables
i. A summary statistics table for each numerical variable
ii. A data frame that contains each pair of variable names and the associated r-square value.
iii. A data frame that contains each pair of variable names and correlation coefficient (Pearson) for all coefficients whose absolute value is greater than the correlation threshold (do not repeat any pairs)
5) Test your function by Using the diamonds data frame you extended to include the VS logical column, a vector of bin sizes (5, 20, 50), and a correlation threshold of 0.25. Also test your function using the mtcars data.
******

I am sorry I don't state my answers exactly in order.
And I have memoed them in the comments.

```{r}
library(ggplot2)  # read ggplot2 library
data("mtcars")    # read "mtcars" data.frame to ehvironment 
require('grid')   # read grid 
data("diamonds")  # read "diamonds" data.frame to ehvironment 


explore<-function(dt,bnsz,thd)
  # Name a function(dt,bnsz,thd) as explore(), and there are three variables.
  # takes a data frame, a vector of bin sizes, and a correlation threshold as input parameters.
  {
  
  r1=list() # define a new blank list(), and names r1.
  c=1       # Set the initial value of c = 1
  
  
  # This is the first question. We will plot a pair of blue histograms in countability method and density method.
  
  vn <- as.numeric(sapply(dt,is.numeric))
  # (dt,is.numeric) means : Extract all of the numeric variables in our data.frame: dt. 
  # sapply(dt,is.numeric) : to determine if the variable is numeric and return True or False.
  # as.numeric() translate our True to 1, False to 0.
  # Therefore, as.numeric(sapply(dt,is.numeric)) will translate all of the variables in dt to numbers 0 or 1          where 0 represent non-numeric, 1 represent numeric. And we just name this as vn. 


  for(i in 1:length(bnsz)){
   #  Let i loop through 1 to the length of vector bnsz
  for(j in 1:length(vn)){
    # Let j loop through 1 to the length of vn.
    if(vn[[j]]==1){      # if vn[j] is numeric
    m=mean(dt[[j]])      # we let m to be the mean of jth column of dt.
    ml = sprintf("$%3.2f ", m)    # m1 is a version of m round to two decimals.
    bins <- (max(dt[,j])-min(dt[,j]))/bnsz[i]  
    # bnsz[i] : the number of bins at each i.
    # (max(dt[,j])-min(dt[,j]))/bnsz[i] is the width of each bin. 
    
    xLabel <- colnames(dt)[j] 
    # lable x-axis with the name of the jth column name of dt 
    h<-ggplot(dt,aes_string(xLabel))
    # read the data of the vector named xLabel in dt and use these data to ggplot 
    h<-h+   # Use h and add all of follows to complete the ggplot.
        geom_histogram(colour='blue',fill='blue',binwidth=bins)+
        # Draw a histogram graph with blue and then fill each rectangle with blue and then let width of bin equal to bins.
        labs(x=colnames(dt)[j]) + 
        # Label x-axis in each graph as the jth column name of dt.
        geom_vline(xintercept=m, colour='red') +
        # Add a red verticle line whose intercept is m (the mean of jth column of dt)
        annotate("text",x=m,y=10,label=ml,hjust=0)
        # Add a text to this graph : add ml at the point (m,10)
        nm=paste('bin=',bnsz[i],colnames(dt)[j],"count.png")
        # Output the graph by png vertion and name the file as the binsize and column name. (use nm to record)
        # For example, "bin= 20 z count.png"
    ggsave(filename = nm)
        # Save the filmname.
    
    
    h2<-ggplot(dt,aes_string(xLabel))
        # read the data of the vector named xLabel in dt and use these data to ggplot 
    h2<-h2+    # Use h2 and add all of follows to complete the ggplot.
      geom_histogram(aes(y=..density..),colour='blue',fill='blue',binwidth=bins)+
      # Use the density method to draw a histogram graph with blue and then fill each rectangle with blue and then let width of bin equal to bins.
      labs(x=colnames(dt)[j]) +
      # Label x-axis in each graph as the jth column name of dt.
      geom_vline(xintercept=m, colour='red') +
      # Add a red verticle line whose intercept is m (the mean of jth column of dt)
      annotate("text",x=m,y=10,label=ml,hjust=0)
      # Add a text to this graph : add ml at the point (m,10)
      nm=paste('bin=',bnsz[i],colnames(dt)[j],"denstity.png")
      # Output the graph by png vertion and name the file as the binsize and column name. (use nm to record)
      # For example, "bin= 20 z density.png"
    ggsave(filename = nm)       # Save the filename.
    }
    
  } 
  }
  
  # This is part of the second question. I will Plot a gray bar graph for every binary variable. 
  
  for(i in 1:ncol(dt)){
    # Let i loop through 1 to the number of columns in dt.
    if(vn[[i]]==1){
      # Use the vn we get in last question, if a data in dt corresponding to vn[i] is numeric,
      if(sum(dt[i]==0)+sum(dt[i]==1)==nrow(dt)){
        # In ith column of dt, if the number of 0 and the number of 1 add up to the number of columns in dt.
        # Then we can have the ith column of dt is binary.
        xLabel <- colnames(dt)[i]
         # lable x-axis with the name of the ith column name of dt 
        ggplot(dt,aes_string(xLabel)) +
          # read the data of the vector named xLabel in dt and use these data to ggplot.
          geom_bar(fill="gray") +      # Draw a bar graph with gray bars
          ggtitle(colnames(dt)[i])+    # Give the title of each graph as the ith column names of dt.
          labs(x=colnames(dt)[i])      # Label x-aes in each graph as the ith column names of dt
          nm=paste(colnames(dt)[i],'.png',sep='')
          # Output the graph by png vertion and name the file as the ith column name of dt.
          # For example, "clarity.png"
          ggsave(filename = nm) 
          # Save the filename.
          
          
  # This is the part a in 4th question.  (binary variable frequency table)
          
        r1[[c]]=table(dt[[i]])  
        # We still use the procedure above.
        # Input every binary column in dt to r1[[c]]. (we know that the initial value of c is 1)
        c=c+1
        # Let c be added 1 every time, that is to record the frequncy of dt and put them to list r1().
      }
    }
  }
  
  
 
  # This is part of the second question. I will Plot a gray bar graph for every categorical variable. 
  
  vc<-as.numeric(sapply(dt,is.factor))+as.numeric(sapply(dt,is.logical))
  # (dt,is.factor) means : Extract all of the factor variables in our data.frame: dt. 
  # (dt,is.logical) means : Extract all of the logical variables in our data.frame: dt. 
  # sapply(dt,is.factor) : to determine if the variable is factor and return True or False.
  # sapply(dt,is.logical) : to determine if the variable is logical and return True or False.
  # as.numeric() translate our True to 1, False to 0.
  # Therefore, as.numeric(sapply(dt,is.factor)) will translate all of the variables in dt to numbers 0 or 1          where 0 represent non-factor, 1 represent factor. 
  # as.numeric(sapply(dt,is.factor)) will translate all of the variables in dt to numbers 0 or 1 where 0 represent non-logical, 1 represent logical.
  # And we name the sum of these two by vc.
  
  
    for(i in 1:length(vc)){
      # Let i loop through 1 to the length of vc.
    if(vc[[i]]>=1){
      # Use the vc we get in last question, if a data in dt corresponding to vn[i] is not both non-factor and non-ligical,
      xLabel <- colnames(dt)[i]        # lable x-axis with the name of the ith column name of dt 
    ggplot(dt,aes_string(xLabel)) +    
    # read the data of the vector named xLabel in dt and use these data to ggplot.
    geom_bar(fill="gray") +          # Draw a bar graph with gray bars
    ggtitle(colnames(dt)[i])+        # Give the title of each graph as the ith column names of dt.
    labs(x=colnames(dt)[i])          # Label x-aes in each graph as the ith column names of dt
    nm=paste(colnames(dt)[i],'.png',sep='')
    # Output the graph by png vertion and name the file as the ith column name of dt.
    # For example, "clarity.png"
    ggsave(filename = nm)  
    # Save the filename.
    
    
    # This is also part a in 4th question. (categorical variable frequency table)
    
    
    r1[[c]]=table(dt[[i]])
     # We still use the procedure above.
     # Input every categorical column in dt to r1[[c]]. 
        c=c+1
        # We know that there is already a list r1, and c is not 1 yet.
        # So we just add new data into list r1, and let c continue to be added 1 every time to record the frequency of categorical column in dt.
        
     }
    }
  
  
  
  # This is part b of 4th question.
  
   r2=list()     # define a new blank list(), and names r1.
   c=1           # Set the initial value of c = 1
   
    for(j in 1:length(vn)){
      # Let i loop through 1 to the length of vn (we defined vn as above) 
    if(vn[[j]]==1){
      # Use the vn we get in last question, if a data in dt corresponding to vn[j] is numeric,
    r2[[c]]=summary(dt[[j]])
      #  A summary statistics table for each numerical variable
    c=c+1  # Let c add up 1 every time, so we can get data in list r2 in order.
    }
  }
  
    r3 = list()   # define a new list, names r3.
    r3[[1]]=r1    
    r3[[2]]=r2    # Let r3 contain list r1 and r2.
    
    #!!!! r1 is teh answer of part a of 4th question.
    #     r2 is 4th question, part b) i)
    
     
    nv=dt[sapply(dt,is.numeric)]
    # Extrate all the numeric data from dt 
    tmp=numeric(0)
    # Set the initial value of tmp
    for(i in 1:ncol(combn((1:ncol(nv)),2))){
    # (combn((1:ncol(nv)),2)) is to produce combinations of every pair of variables in  the data frame "nv"
    # ncol(combn((1:ncol(nv)),2)) is to count the number of pairs of variables as above.
    # i steps one by one from 1 to the total number of pairs of variables.
    tmp=c(tmp,cor(nv[[combn((1:ncol(nv)),2)[1,i]]],nv[[combn((1:ncol(nv)),2)[2,i]]]))
    # Calculate the correlation coefficient of every pair of the variables, and then put these values to the column "tmp"
    }
    
    n=paste(combn(colnames(nv),2)[1,],'-',combn(colnames(nv),2)[2,],sep='')
     # define the first column--the corresponding variables of each corelation coefficient. And we give these names by paste them with a "-".
    r3[[3]]=data.frame(n,tmp)
     # Creat a new data frame with the "n" column and the "tmp" column, say r3[[3]]
     # r3[[3]] is the answer of 4th question part b), ii). And it is also the answer of question 3.
    
    
    tmp2=tmp*tmp           # Define tmp2 as square of tmp
    tmp2=tmp2[tmp2>thd]    
    # Determine all of the data in tmps if them are > thd (the input variable) , if yes, then let these data be new tmp2. That is what we want.
    n=n[tmp*tmp>thd]
    # Also extract the name of data corresponding to those in tmp2 who > thd.
    r3[[4]]=data.frame(n,tmp2)
    # Conbine n and tpm2 together to be r3[[4]], which is the answer of 4th question part b), iii).
  
  
  return(r3)  # return r3, we get all of the answer of question 3 & 4.
    
  }
    
# This is the 5th quesion, we test our function by the given example : a vector of bin sizes (5, 20, 50), a correlation threshold of 0.25 and  the mtcars data.

  diamonds$vs<-rep((mtcars$vs==1)[3:22],2697)  # Add the vs logical column in mtcart to diamonds data frame.
  test1=explore(diamonds,c(5,20,50),0.25)  
  test1     # Output the list.
  test2=explore(mtcars,c(5,20,50),0.25)    
  test2     # Output the list.
  